[meta]
name     = "Dips++"
author   = "XertroV"
category = "Deep Dip 2"
version  = "0.4.18"
siteid   = 519

[script]
#__DEFINES__
dependencies = ["VehicleState", "Camera"]
optional_dependencies = ["betterloadingscreen", "customloadingscreen", "static-loading-screen", "MLHook"]
